- name: ä¸­æ–‡(ç¹é«”)
  code: zh-tw
  description: Bootstrap 4 ç¹é«”ä¸­æ–‡æ‰‹å†Š
  url: https://bootstrap.hexschool.com/

- name: Chinese
  code: zh
  description: Bootstrap 4 Â· å…¨çƒæœ€æµè¡Œçš„ HTMLã€CSS å’Œ JS å·¥å…·åº“ã€‚
  url: https://code.z01.com/v4/

- name: Brazilian Portuguese
  code: pt-BR
  description: Bootstrap 4 PortuguÃªs do Brasil
  url: https://getbootstrap.com.br/v4/

- name: Japanese
  code: ja
  description: Bootstrap 4 æ—¥æœ¬èªãƒªãƒ•ã‚¡ãƒ¬ãƒ³ã‚¹
  url: https://getbootstrap.jp/

- id: gb
  name: English
  flag: ğŸ‡¬ğŸ‡§
- id: zh_cn
  name: ç®€ä½“ä¸­æ–‡
  flag: ğŸ‡¨ğŸ‡³
- id: fi
  name: Suomen
  flag: ğŸ‡«ğŸ‡®
